### 二维码账户信息
POST {{url}}/upc/qrcode/account/info
Accept : application/json
Content-Type: application/json
Cache-Control : no-cache
Signature: iJ2CNYvD18JDPzhB8mrH0kEOdht0D/5LAR9bKfKaCWKITmGhUUrtF7X2kvVOTQ3yEJGbuLR2GEvwIgudf94jxLYk7GHVH9wHow6L5j6JlIYeDCeobz1WRV3DIpzIp4yaGDuABPbVsq3pMxAKFGcIRFYSrT1g+sZyzZFATPTw87s=

{"userId":"100101"}

### 获取二维码
POST {{url}}/upc/qrcode/get
Accept : application/json
Content-Type: application/json
Cache-Control : no-cache
Signature: Ei4ABQRHYy0+gLIwstDl/Q1BwiTqZabQE0ptcuA/hFYVPhmqJOzimLoQNvxH5tbYBC4ij4bavm0dnT7H2cNqiLyQ0cPViivwTgQ/M/VAhiVxlxI3fEqjopw+JAz38vI3MxWkSHTi52IJVZzs4yJG+EPZiTmf5nfhLvV3ukvp+NQ=

{"userId":"5433"}

### 行程数据通知
POST {{url}}/upc/trip/sync
Accept : application/json
Content-Type: application/json
Cache-Control : no-cache
Signature: QXaFdPWl+ESOC3g0u1X0dlOYVIjmtgMiBB+KqC+ZaToGXzBR9ZNAdb71g7pwBs8+06NKIwXlFx1XiKSQxRjY99nuE3NM4DCXZIp9kxMgMYnU+ZVSwNDL/mVQ3nL5FMbZAODlHWticJaicv4seRBLvkK2jVtpoaiq0V+SohPoQTw=

{"order_no":"2018051340345213038069443","fellow_no":10001,"in_qrcode_data":"as231d321sad23sa3d","in_sys_lng":12.323232,"op_id":10001,"in_voucher_no":"111","trip_no":"2433670599541761","in_sys_lat":52.0,"userId":5433,"in_line_no":"123132","outLineNo":"1","in_station_name":"151515","in_sys_time":1526283921794,"in_time":1526283921794,"in_station_no":"123123","out_qrcode_data":"1as32d123as1d23asd","service_id":"0200","in_status":"1","out_voucher_no":2,"in_confirm_type":1}

### 行程消费扣款请求
POST {{url}}/upc/trip/consume
Accept : application/json
Content-Type: application/json
Cache-Control : no-cache
Signature: hWiblda5xQkgjuF6loHPlZdO6iEAKhh/Tf6Rvv+40yyrE+Ljv2MrdKvtMHDEyZNlhhMTBF7VMzBHgkDH+kUKmCBQi1/OAEiFMdj+jLwKRpWNeWZMdTzIIZ+E1DxNbJMsllR3hORPSnIS7UHdWiLrZAjAV5EDBPGq1/YJQ3nJIjs=

{"order_no":"1805091700000011","fellow_no":"0000000000000000","discount_desc":"null","discount_amount":0,"fine_desc":"null","fee_mode":1,"op_id":"C450320182000001","trans_time":"20180423174641","trip_no":"2388761025512448","trans_amount":200,"settlement_mode":1,"settlement_sts":1,"base_amount":200,"settlement_amount":188,"fine_amount":0}


### 开启免密支付
POST {{url}}/upc/epp/open
Accept : application/json
Content-Type: application/json
Cache-Control : no-cache
Signature: dOzLLhqHXmbMMn9sE5B3mAj0k0j2Jmm9+8ZSQHZjRSeYF+wtoV1cLcyWZugjoUSJhYxdEIBRrw1q0w9pIOuOWqJV0bqJLg3lhlFTG+SvyDyK6qnLLFTYAYSd+IIEraeQG0SSjusQcREwuQAXDMeQGvlMWnq6piEm422NLueQT2c=

{"confirmPayPassword":"WTFkRVJsRjVkVGwwUXpROQ==","userId":"5433","payPassword":"WTFkRVJsRjVkVGwwUXpROQ=="}

### 关闭免密支付
POST {{url}}/upc/epp/close
Accept : application/json
Content-Type: application/json
Cache-Control : no-cache
Signature: cw4FovkIUjH5XyWDTlGzIDJ3lLXTZujJDPciCcO3TRSXImdstgh3oEByOPOHjihb5vE7dAdTh+0GzTMPr3+PHvORq8BiXJzzn/5OkyQdp4nCua8g9u3/nd1WXgSW4Zp1uElF+25Gzgmh1pMWqQsL6CWM3/ETNzrEAvzZAkMWuII=

{"userId":"5433","payPassword":"WTFkRVJsRjVkVGwwUXpROQ=="}

###